server:
  port: 8082

spring:
  application:
    name: user-service
  messages:
    encoding: utf-8

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/consort_group
    username: consort
    password: 2231251fsad1
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_versioned_data: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6383

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

kafka:
  bootstrap-servers: localhost:9092
  consumer-group-id: email-group
  session-timeout-ms: 10000
  max-partition-fetch-bytes: 1048576
  max-poll-records: 500
  max-poll-interval-ms: 300000
  user-registration: user-registered-topic
  user-update-profile: user-update-profile-topic
  verification-code-resent: verification-code-resent-topic
  password-reset-request: password-reset-request-topic

security:
  token: wUIBjx3G1C1Ee+eIXtt/zVIFkS40lhoan0HgHriNERBL08Vv2Bwb92is6gZUGEzANhMXulAPHD9li4TmKrdDoA==
  expiration: 3600000

async:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 15
  thread-name-prefix: notification-service

notification:
  email:
    chunk-size: 1000
    max-concurrent-emails: 100

mail:
  host: smtp.gmail.com
  port: 587
  username: doniyor.kurbanov.21@gmail.com
  password: eeqm amxf ejqc dahi
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
  subjectForEmail: "Registration code"


user:
  service:
    url: http://localhost:8081
