CREATE TABLE IF NOT EXISTS notification_schema.user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    language VARCHAR(5),
    last_name VARCHAR(120) NOT NULL,
    first_name VARCHAR(120) NOT NULL,
    middle_name VARCHAR(120) NOT NULL,
    born_date DATE NOT NULL,
    phone_number VARCHAR(13) NOT NULL,
    email VARCHAR(120) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    notification_status VARCHAR(50) DEFAULT NULL,
    communication_method VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    version INT DEFAULT 0
)