CREATE TABLE IF NOT EXISTS notification_schema.user_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_last_name VARCHAR(120) NOT NULL,
    user_first_name VARCHAR(120) NOT NULL,
    user_middle_name VARCHAR(120) NOT NULL,
    user_phone_number VARCHAR(13) NOT NULL,
    user_date_of_birth DATE NOT NULL,
    user_email VARCHAR(120) NOT NULL,
    verification_code VARCHAR(4) NOT NULL
)